### ISSUE TITLE
finalization: plugin system

### ISSUE THREAD

**Issue by thejatmik** [thejatmik/uH2gYcfki4gFpM#8]
## Plugin definition
it is a set of script that,
- can define and create ipc process
  - define where ipc handler will be installed
  - define what ipc handler will do
- can define and create ui
  - create react component/view page
  - mount said component/view page in react router
- can use other utilities,via an `import ...` line in the right process scope
  - `electron-store`, in main process
  - `BaseStore`, in main process
  - `types/*`, in main process
  - `cesium`, in renderer process

### when I create "plugin"
- i want to access rpc
  exposes rpc are `window.store`, `window.electron`, and `window.electronWindow`
  there should be a method so user can create their own rpc and expose it by importing from rootDir or something equivalent
- i want to create react component then mount to this-particular url
  WindowManager seems a bit confusing without explanation... 

## TODOs
- [x] "Hello world" plugin template
  Plugin that create page with a button that log "Hello world" on click.
- [x] refactor: move all global types to `./src/types/*`
- [ ] idea: add view that list enabled plugin, will act as entry point instead of hardcoding renderer/Front component

### Plugin example
```js
// ./src/havent/thought/about/folder/structure/yet/index.ts
// here user import utilities
import Plugin, { IpcHandler } from 'src.plugin';
import BaseStore from 'src.main';

// here user import their plugin component
import ipc from './myIpc'; // --> type of IpcHandler
import MyView from './MyViews'; // --> JSX.Element
import myStore from './myStore'; // extension of BaseStore

const myPlugin = new Plugin();

myPlugin.main = { // 'main' addressing main process
  ipcHandler: ipc,
  store: myStore,
};
myPlugin.ui = { // 'ui' adressing renderer process
  routeName: MyView,
}

export default myPlugin; // i guess default export for one plugin
```
